// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartShop.Modules.Shops.Data;

#nullable disable

namespace SmartShop.Modules.Shops.Data.Migrations
{
    [DbContext(typeof(ShopsDbContext))]
    [Migration("20261004131948_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shops")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartShop.Modules.Shops.Domain.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("account_number");

                    b.Property<string>("BankName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("bank_name");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("instructions");

                    b.Property<string>("PromptPayId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prompt_pay_id");

                    b.Property<Guid?>("QrImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("qr_image_id");

                    b.Property<bool>("RequiresProof")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_proof");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_payment_methods");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_payment_methods_shop_id");

                    b.ToTable("payment_methods", "shops");
                });

            modelBuilder.Entity("SmartShop.Modules.Shops.Domain.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcceptMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("accept_mode");

                    b.Property<int>("AcceptTimeoutMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("accept_timeout_minutes");

                    b.Property<bool>("AllowPreorderWhenClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_preorder_when_closed");

                    b.Property<int>("AutoCompleteHours")
                        .HasColumnType("integer")
                        .HasColumnName("auto_complete_hours");

                    b.Property<DateTimeOffset?>("BusyUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("busy_until");

                    b.Property<string>("Category")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("code");

                    b.Property<Guid?>("CoverId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DeliveryEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("delivery_enabled");

                    b.Property<decimal?>("DeliveryMinOrder")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("delivery_min_order");

                    b.Property<string>("DeliveryZoneNote")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("delivery_zone_note");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("HouseNo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("house_no");

                    b.Property<string>("LineContact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("line_contact");

                    b.Property<Guid?>("LogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("logo_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("OverrideMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("override_mode");

                    b.Property<DateTimeOffset?>("OverrideUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("override_until");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<bool>("PickupEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("pickup_enabled");

                    b.Property<string>("PickupInstruction")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("pickup_instruction");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("prep_time_minutes");

                    b.Property<decimal>("RatingAverage")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rating_average");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer")
                        .HasColumnName("rating_count");

                    b.Property<int>("ReminderAfterMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("reminder_after_minutes");

                    b.Property<bool>("RequirePaymentBeforePreparing")
                        .HasColumnType("boolean")
                        .HasColumnName("require_payment_before_preparing");

                    b.Property<int>("SlotIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("slot_interval_minutes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("SuspendReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspend_reason");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("VacationMessage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vacation_message");

                    b.Property<DateTimeOffset?>("VacationUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vacation_until");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_shops");

                    b.HasIndex("PlantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_shops_plant_id_code");

                    b.ToTable("shops", "shops");
                });

            modelBuilder.Entity("SmartShop.Modules.Shops.Domain.ShopApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid")
                        .HasColumnName("applicant_id");

                    b.Property<string>("Category")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("HouseNo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("house_no");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.PrimitiveCollection<List<Guid>>("SampleImageIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("sample_image_ids");

                    b.Property<Guid?>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("ApplicantId")
                        .HasDatabaseName("ix_applications_applicant_id");

                    b.HasIndex("PlantId", "Status")
                        .HasDatabaseName("ix_applications_plant_id_status");

                    b.ToTable("applications", "shops");
                });

            modelBuilder.Entity("SmartShop.Modules.Shops.Domain.ShopClosure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.HasKey("Id")
                        .HasName("pk_closures");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_closures_shop_id");

                    b.ToTable("closures", "shops");
                });

            modelBuilder.Entity("SmartShop.Modules.Shops.Domain.ShopFavorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "ShopId")
                        .HasName("pk_favorites");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_favorites_shop_id");

                    b.ToTable("favorites", "shops");
                });

            modelBuilder.Entity("SmartShop.Modules.Shops.Domain.ShopInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.HasKey("Id")
                        .HasName("pk_invites");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_invites_code");

                    b.ToTable("invites", "shops");
                });

            modelBuilder.Entity("SmartShop.Modules.Shops.Domain.ShopMember", b =>
                {
                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("DisplayLabel")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("display_label");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<bool>("ReceiveOrderNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("receive_order_notifications");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("ShopId", "UserId")
                        .HasName("pk_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_members_user_id");

                    b.ToTable("members", "shops");
                });

            modelBuilder.Entity("SmartShop.Modules.Shops.Domain.ShopStatusTracker", b =>
                {
                    b.Property<Guid>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("LastAnnouncedState")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("last_announced_state");

                    b.Property<DateTimeOffset?>("NextEvaluationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_evaluation_at");

                    b.HasKey("ShopId")
                        .HasName("pk_status_trackers");

                    b.ToTable("status_trackers", "shops");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_incoming_envelopes");

                    b.ToTable("wolverine_incoming_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_outgoing_envelopes");

                    b.ToTable("wolverine_outgoing_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SmartShop.Modules.Shops.Domain.PaymentMethod", b =>
                {
                    b.HasOne("SmartShop.Modules.Shops.Domain.Shop", null)
                        .WithMany("PaymentMethods")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_methods_shops_shop_id");
                });

            modelBuilder.Entity("SmartShop.Modules.Shops.Domain.Shop", b =>
                {
                    b.OwnsMany("SmartShop.Modules.Shops.Domain.OpeningHour", "Hours", b1 =>
                        {
                            b1.Property<Guid>("ShopId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<TimeOnly>("CloseAt");

                            b1.Property<int>("Day");

                            b1.Property<TimeOnly>("OpenAt");

                            b1.HasKey("ShopId", "__synthesizedOrdinal")
                                .HasName("pk_shops");

                            b1.ToTable("shops", "shops");

                            b1
                                .ToJson("hours")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ShopId")
                                .HasConstraintName("fk_shops_shops_shop_id");
                        });

                    b.Navigation("Hours");
                });

            modelBuilder.Entity("SmartShop.Modules.Shops.Domain.ShopClosure", b =>
                {
                    b.HasOne("SmartShop.Modules.Shops.Domain.Shop", null)
                        .WithMany("Closures")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_closures_shops_shop_id");
                });

            modelBuilder.Entity("SmartShop.Modules.Shops.Domain.ShopMember", b =>
                {
                    b.HasOne("SmartShop.Modules.Shops.Domain.Shop", null)
                        .WithMany("Members")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_members_shops_shop_id");
                });

            modelBuilder.Entity("SmartShop.Modules.Shops.Domain.Shop", b =>
                {
                    b.Navigation("Closures");

                    b.Navigation("Members");

                    b.Navigation("PaymentMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
