<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>SmartShop.Worker</RootNamespace>
    <UserSecretsId>smartshop-worker</UserSecretsId>
    <ContainerRepository>smartshop-worker</ContainerRepository>
    <ContainerFamily>noble-chiseled-extra</ContainerFamily>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SmartShop.Bootstrap\SmartShop.Bootstrap.csproj" />
  </ItemGroup>
</Project>
