<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\SmartShop.SharedKernel\SmartShop.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\Modules\SmartShop.Modules.Payments\SmartShop.Modules.Payments.csproj" />
    <ProjectReference Include="..\..\src\Modules\SmartShop.Modules.Ordering\SmartShop.Modules.Ordering.csproj" />
    <ProjectReference Include="..\..\src\Modules\SmartShop.Modules.Catalog\SmartShop.Modules.Catalog.csproj" />
  </ItemGroup>
</Project>
