<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>SmartShop.Api</RootNamespace>
    <UserSecretsId>smartshop-api</UserSecretsId>
    <ContainerRepository>smartshop-api</ContainerRepository>
    <ContainerFamily>noble-chiseled-extra</ContainerFamily>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SmartShop.Bootstrap\SmartShop.Bootstrap.csproj" />
  </ItemGroup>
</Project>
