// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartShop.Modules.Ordering.Data;

#nullable disable

namespace SmartShop.Modules.Ordering.Data.Migrations
{
    [DbContext(typeof(OrderingDbContext))]
    [Migration("20261004133523_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ordering")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartShop.Modules.Ordering.Data.OrderCounter", b =>
                {
                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("Last")
                        .HasColumnType("integer")
                        .HasColumnName("last");

                    b.HasKey("ShopId", "Day")
                        .HasName("pk_order_counters");

                    b.ToTable("order_counters", "ordering");
                });

            modelBuilder.Entity("SmartShop.Modules.Ordering.Domain.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_carts");

                    b.HasIndex("UserId", "PlantId")
                        .IsUnique()
                        .HasDatabaseName("ix_carts_user_id_plant_id");

                    b.ToTable("carts", "ordering");
                });

            modelBuilder.Entity("SmartShop.Modules.Ordering.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by");

                    b.Property<DateTimeOffset?>("AutoCompleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auto_complete_at");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cancel_reason");

                    b.Property<string>("CancelRequestReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cancel_request_reason");

                    b.Property<DateTimeOffset?>("CancelRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancel_requested_at");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid?>("DeliveryPhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_photo_id");

                    b.Property<decimal>("Discount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("discount");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FulfillmentType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("fulfillment_type");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("order_no");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_method_id");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("payment_method_name");

                    b.Property<string>("PaymentMethodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_method_type");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("payment_status");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<Guid?>("PreOrderRoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("pre_order_round_id");

                    b.Property<string>("PromotionCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("promotion_code");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.Property<DateTimeOffset?>("ScheduledFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_from");

                    b.Property<DateTimeOffset?>("ScheduledTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_to");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("shop_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("PreOrderRoundId")
                        .HasDatabaseName("ix_orders_pre_order_round_id");

                    b.HasIndex("CustomerId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_customer_id_idempotency_key");

                    b.HasIndex("CustomerId", "PlacedAt")
                        .HasDatabaseName("ix_orders_customer_id_placed_at");

                    b.HasIndex("PlantId", "PlacedAt")
                        .HasDatabaseName("ix_orders_plant_id_placed_at");

                    b.HasIndex("ShopId", "OrderNo")
                        .HasDatabaseName("ix_orders_shop_id_order_no");

                    b.HasIndex("ShopId", "Status", "PlacedAt")
                        .HasDatabaseName("ix_orders_shop_id_status_placed_at");

                    b.ToTable("orders", "ordering");
                });

            modelBuilder.Entity("SmartShop.Modules.Ordering.Domain.OrderMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<bool>("FromShop")
                        .HasColumnType("boolean")
                        .HasColumnName("from_shop");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("OrderId", "SentAt")
                        .HasDatabaseName("ix_messages_order_id_sent_at");

                    b.ToTable("messages", "ordering");
                });

            modelBuilder.Entity("SmartShop.Modules.Ordering.Domain.OrderReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<string>("Resolution")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("PlantId", "Status")
                        .HasDatabaseName("ix_reports_plant_id_status");

                    b.ToTable("reports", "ordering");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_incoming_envelopes");

                    b.ToTable("wolverine_incoming_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_outgoing_envelopes");

                    b.ToTable("wolverine_outgoing_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SmartShop.Modules.Ordering.Domain.Cart", b =>
                {
                    b.OwnsMany("SmartShop.Modules.Ordering.Domain.CartLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("CartId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("Id");

                            b1.Property<Guid>("ItemId");

                            b1.Property<string>("Note");

                            b1.PrimitiveCollection<string>("OptionIds")
                                .IsRequired();

                            b1.Property<int>("Quantity");

                            b1.Property<DateTimeOffset?>("SlotStart");

                            b1.HasKey("CartId", "__synthesizedOrdinal")
                                .HasName("pk_carts");

                            b1.ToTable("carts", "ordering");

                            b1
                                .ToJson("lines")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CartId")
                                .HasConstraintName("fk_carts_carts_cart_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SmartShop.Modules.Ordering.Domain.Order", b =>
                {
                    b.OwnsOne("SmartShop.Modules.Ordering.Domain.DeliveryAddress", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId");

                            b1.Property<string>("HouseNo");

                            b1.Property<string>("Note");

                            b1.Property<string>("Soi");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders", "ordering");

                            b1
                                .ToJson("delivery_address")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_orders_orders_id");
                        });

                    b.OwnsMany("SmartShop.Modules.Ordering.Domain.OrderEvent", "Timeline", b1 =>
                        {
                            b1.Property<Guid>("OrderId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid?>("ActorId");

                            b1.Property<DateTimeOffset>("At");

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Note");

                            b1.Property<Guid?>("PhotoId");

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.HasKey("OrderId", "__synthesizedOrdinal")
                                .HasName("pk_orders");

                            b1.ToTable("orders", "ordering");

                            b1
                                .ToJson("timeline")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_orders_orders_order_id");
                        });

                    b.OwnsMany("SmartShop.Modules.Ordering.Domain.OrderLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("OrderId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("Id");

                            b1.Property<Guid>("ItemId");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Note");

                            b1.Property<int>("Quantity");

                            b1.Property<DateTimeOffset?>("SlotStart");

                            b1.Property<decimal>("UnitPrice");

                            b1.HasKey("OrderId", "__synthesizedOrdinal")
                                .HasName("pk_orders");

                            b1.ToTable("orders", "ordering");

                            b1
                                .ToJson("lines")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_orders_orders_order_id");

                            b1.OwnsMany("SmartShop.Modules.Ordering.Domain.OrderLineOption", "Options", b2 =>
                                {
                                    b2.Property<Guid>("OrderLineOrderId");

                                    b2.Property<int>("OrderLine__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Group")
                                        .IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<decimal>("PriceDelta");

                                    b2.HasKey("OrderLineOrderId", "OrderLine__synthesizedOrdinal", "__synthesizedOrdinal")
                                        .HasName("pk_orders");

                                    b2.ToTable("orders", "ordering");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderLineOrderId", "OrderLine__synthesizedOrdinal")
                                        .HasConstraintName("fk_orders_orders_order_line_order_id_order_line__synthesized_ordinal");
                                });

                            b1.Navigation("Options");
                        });

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Lines");

                    b.Navigation("Timeline");
                });
#pragma warning restore 612, 618
        }
    }
}
