<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SmartShop.Bootstrap</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Aspire\SmartShop.ServiceDefaults\SmartShop.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\SmartShop.Infrastructure\SmartShop.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\SmartShop.Modules.Identity\SmartShop.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\Modules\SmartShop.Modules.Media\SmartShop.Modules.Media.csproj" />
    <ProjectReference Include="..\..\Modules\SmartShop.Modules.Plants\SmartShop.Modules.Plants.csproj" />
    <ProjectReference Include="..\..\Modules\SmartShop.Modules.Shops\SmartShop.Modules.Shops.csproj" />
    <ProjectReference Include="..\..\Modules\SmartShop.Modules.Catalog\SmartShop.Modules.Catalog.csproj" />
    <ProjectReference Include="..\..\Modules\SmartShop.Modules.Ordering\SmartShop.Modules.Ordering.csproj" />
    <ProjectReference Include="..\..\Modules\SmartShop.Modules.Payments\SmartShop.Modules.Payments.csproj" />
    <ProjectReference Include="..\..\Modules\SmartShop.Modules.Notifications\SmartShop.Modules.Notifications.csproj" />
    <ProjectReference Include="..\..\Modules\SmartShop.Modules.Search\SmartShop.Modules.Search.csproj" />
    <ProjectReference Include="..\..\Modules\SmartShop.Modules.Reviews\SmartShop.Modules.Reviews.csproj" />
    <ProjectReference Include="..\..\Modules\SmartShop.Modules.Promotions\SmartShop.Modules.Promotions.csproj" />
    <ProjectReference Include="..\..\Modules\SmartShop.Modules.Audit\SmartShop.Modules.Audit.csproj" />
    <ProjectReference Include="..\..\Modules\SmartShop.Modules.Integrations\SmartShop.Modules.Integrations.csproj" />
  </ItemGroup>
</Project>
