// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartShop.Modules.Catalog.Data;

#nullable disable

namespace SmartShop.Modules.Catalog.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20261004132733_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartShop.Modules.Catalog.Domain.Inventory", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int?>("DailyQuota")
                        .HasColumnType("integer")
                        .HasColumnName("daily_quota");

                    b.Property<TimeOnly?>("DailyResetTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("daily_reset_time");

                    b.Property<DateOnly?>("LastResetDate")
                        .HasColumnType("date")
                        .HasColumnName("last_reset_date");

                    b.Property<bool>("LowStockNotified")
                        .HasColumnType("boolean")
                        .HasColumnName("low_stock_notified");

                    b.Property<int?>("LowStockThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("low_stock_threshold");

                    b.Property<int>("OnHand")
                        .HasColumnType("integer")
                        .HasColumnName("on_hand");

                    b.Property<int>("Reserved")
                        .HasColumnType("integer")
                        .HasColumnName("reserved");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.HasKey("ItemId")
                        .HasName("pk_inventories");

                    b.ToTable("inventories", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_non_negative", "reserved >= 0 AND on_hand >= reserved");
                        });
                });

            modelBuilder.Entity("SmartShop.Modules.Catalog.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<int[]>("AllowedFulfillment")
                        .HasColumnType("integer[]")
                        .HasColumnName("allowed_fulfillment");

                    b.Property<bool>("AnnouncedSoldOut")
                        .HasColumnType("boolean")
                        .HasColumnName("announced_sold_out");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.PrimitiveCollection<List<Guid>>("ImageIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("image_ids");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recommended");

                    b.Property<bool>("IsSoldOut")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sold_out");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<int?>("MaxPerOrder")
                        .HasColumnType("integer")
                        .HasColumnName("max_per_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<Guid?>("PreOrderRoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("pre_order_round_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<DateOnly?>("SaleFrom")
                        .HasColumnType("date")
                        .HasColumnName("sale_from");

                    b.Property<DateOnly?>("SaleTo")
                        .HasColumnType("date")
                        .HasColumnName("sale_to");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<int?>("SlotCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("slot_capacity");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("StockMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("stock_mode");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("ix_items_plant_id");

                    b.HasIndex("PreOrderRoundId")
                        .HasDatabaseName("ix_items_pre_order_round_id");

                    b.HasIndex("ShopId", "DeletedAt")
                        .HasDatabaseName("ix_items_shop_id_deleted_at");

                    b.ToTable("items", "catalog");
                });

            modelBuilder.Entity("SmartShop.Modules.Catalog.Domain.ItemCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_categories_shop_id");

                    b.ToTable("categories", "catalog");
                });

            modelBuilder.Entity("SmartShop.Modules.Catalog.Domain.PreOrderRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("FulfillFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fulfill_from");

                    b.Property<DateTimeOffset>("FulfillTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fulfill_to");

                    b.Property<int?>("MinTotalQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("min_total_quantity");

                    b.Property<DateTimeOffset>("OrderCutoff")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_cutoff");

                    b.Property<int>("OrderedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("ordered_quantity");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_preorder_rounds");

                    b.HasIndex("ShopId", "Status")
                        .HasDatabaseName("ix_preorder_rounds_shop_id_status");

                    b.ToTable("preorder_rounds", "catalog");
                });

            modelBuilder.Entity("SmartShop.Modules.Catalog.Domain.SlotBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<DateTimeOffset>("SlotEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("slot_end");

                    b.Property<DateTimeOffset>("SlotStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("slot_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_slot_bookings");

                    b.HasIndex("ItemId", "SlotStart")
                        .HasDatabaseName("ix_slot_bookings_item_id_slot_start");

                    b.HasIndex("OrderId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_slot_bookings_order_id_item_id");

                    b.ToTable("slot_bookings", "catalog");
                });

            modelBuilder.Entity("SmartShop.Modules.Catalog.Domain.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("note");

                    b.Property<int>("OnHandAfter")
                        .HasColumnType("integer")
                        .HasColumnName("on_hand_after");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("ReservedAfter")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_after");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("ItemId", "At")
                        .HasDatabaseName("ix_stock_movements_item_id_at");

                    b.HasIndex("OrderId", "ItemId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_movements_order_id_item_id_type")
                        .HasFilter("order_id IS NOT NULL");

                    b.ToTable("stock_movements", "catalog");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_incoming_envelopes");

                    b.ToTable("wolverine_incoming_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_outgoing_envelopes");

                    b.ToTable("wolverine_outgoing_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SmartShop.Modules.Catalog.Domain.Item", b =>
                {
                    b.OwnsMany("SmartShop.Modules.Catalog.Domain.AvailabilityWindow", "AvailabilityWindows", b1 =>
                        {
                            b1.Property<Guid>("ItemId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.PrimitiveCollection<string>("Days")
                                .IsRequired();

                            b1.Property<TimeOnly>("From");

                            b1.Property<TimeOnly>("To");

                            b1.HasKey("ItemId", "__synthesizedOrdinal")
                                .HasName("pk_items");

                            b1.ToTable("items", "catalog");

                            b1
                                .ToJson("availability_windows")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ItemId")
                                .HasConstraintName("fk_items_items_item_id");
                        });

                    b.OwnsMany("SmartShop.Modules.Catalog.Domain.ModifierGroup", "ModifierGroups", b1 =>
                        {
                            b1.Property<Guid>("ItemId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("Id");

                            b1.Property<int>("MaxSelect");

                            b1.Property<int>("MinSelect");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("ItemId", "__synthesizedOrdinal")
                                .HasName("pk_items");

                            b1.ToTable("items", "catalog");

                            b1
                                .ToJson("modifier_groups")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ItemId")
                                .HasConstraintName("fk_items_items_item_id");

                            b1.OwnsMany("SmartShop.Modules.Catalog.Domain.ModifierOption", "Options", b2 =>
                                {
                                    b2.Property<Guid>("ModifierGroupItemId");

                                    b2.Property<int>("ModifierGroup__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<Guid>("Id");

                                    b2.Property<bool>("IsAvailable");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<decimal>("PriceDelta");

                                    b2.HasKey("ModifierGroupItemId", "ModifierGroup__synthesizedOrdinal", "__synthesizedOrdinal")
                                        .HasName("pk_items");

                                    b2.ToTable("items", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("ModifierGroupItemId", "ModifierGroup__synthesizedOrdinal")
                                        .HasConstraintName("fk_items_items_modifier_group_item_id_modifier_group__synthesized_o");
                                });

                            b1.Navigation("Options");
                        });

                    b.Navigation("AvailabilityWindows");

                    b.Navigation("ModifierGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
